### ISSUE TITLE
Literature review of the benefits of open-science research

### ISSUE THREAD

**Issue by jvohryzek** [cassgvp/WIN-Open-Neuroimaging-Community#11]
Motivating the benefits of open-science with some relevant literature sources.

**Comment by cassgvp** [comment]
thank you for this @jvohryzek . I'm going to link this to #6 as they are very similar and close this, if you agree?

**Comment by jvohryzek** [comment]
> thank you for this @jvohryzek . I'm going to link this to #6 as they are very similar and close this, if you agree?

Yes @cassgvp . It makes a lot of sense!
