### ISSUE TITLE
Contributing Guide on Readme points to a 404 error

### ISSUE THREAD

**Issue by Ruth-ikegah** [cassgvp/WIN-Open-Neuroimaging-Community#26]
**Current behaviour**
The contributing guideline on the Readme points to a 404 error page. 

**Desired Behaviour**
Change the link on the readme to the correct one
Actual link for [contributing guidelines](https://cassgvp.github.io/WIN-Open-Neuroimaging-Community/docs/CONTRIBUTING.html)

**Comment by cassgvp** [comment]
thanks for flagging this! I've updated the path in 3f5a75c072a243ba89bfbe8e5aa6a9c0916ee32a
