### ISSUE TITLE
Broken link to Ambassador's in README  

### ISSUE THREAD

**Issue by Anita-ihuman** [cassgvp/WIN-Open-Neuroimaging-Community#27]
### Current Behaviour
The link that directs visitors to this community on becoming an ambassador keeps displaying Error 404.
### Desired Behaviour
Fix the link on the README to the correct one.

**Comment by cassgvp** [comment]
Thank you for flagging this :). I have corrected the link in  0af86084c0f78eb090fd146ec2d60b1bd9c87a21
