### ISSUE TITLE
The link to Mailing list is broken

### ISSUE THREAD

**Issue by Anita-ihuman** [cassgvp/WIN-Open-Neuroimaging-Community#28]
### Current Behaviour
The links to the mailing list on the website and README seem to be displaying "This site can’t be reached"
### Desired Behaviour
Fix the link on the Website & README to the correct one.

**Comment by cassgvp** [comment]
Thank you for flagging this! It seems that the mailing list is open only to Oxford staff and students. I have corrected the description in cf81db924bb76a37f54666f42962f6c32f24669b.
