### ISSUE TITLE
make slack join link more prominent

### ISSUE THREAD

**Issue by cassgvp** [cassgvp/WIN-Open-Neuroimaging-Community#9]
Comment from @mchiew on issue #1:

> Just a comment after attempting to find and join the Slack. I think a "Join the OpenWIN Slack" link or button on the main home page might be useful. My first instinct was to click on the "Community" heading, but joining the Slack didn't seem to be in any of those pages. I clicked around a bit, but I had trouble finding it even knowing it existed somewhere. I finally resorted to the Search function, which did work, but isn't super discoverable for those not already looking for a Slack.

Consider renaming "Join the community" link on page headers to "Join us on Slack or by Email"

**Comment by Ruth-ikegah** [comment]
Please can I take this up?

**Comment by cassgvp** [comment]
Sure! You are very welcome to :)

**Comment by cassgvp** [comment]
I've also updated the config file to update the link at the top of each page, in 901f061be6fb51ebbcd57649ef41c50c76ffccc5
